

spring.datasource.url=jdbc:mysql://localhost:3306/airportdb
spring.datasource.username=root
spring.datasource.password=sriharini007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8082
spring.thymeleaf.cache=false